spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/etfb_db_bu1
    url: jdbc:mysql://192.168.1.48:3306/etfb_db_bu1
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password:
    username: etf
    password: ETF#Mysqldevba123
    #password: shan123
